### ISSUE TITLE
Seeking to join the W3ID Consortium

### ISSUE THREAD

**Issue by nicholascar** [perma-id/w3id.org#1954]
As per my request to the W3ID mailing list [1], I wish to have [SURROUND Australia Pty Ltd](https://surroundaustralia.com) join the W3ID Consortium and have been advised by existing members via email that I should open an Issue like this.

So, please allow SURROUND in! Thanks.

[1] https://lists.w3.org/Archives/Public/public-perma-id/2020Dec/0004.html

**Comment by dgarijo** [comment]
I don't have privileges to allow this, @davidlehn, do you have any objections?
I think it's great to have more support to help curating and maintaining w3id.org.

**Comment by kidehen** [comment]
> As per my request to the W3ID mailing list [1], I wish to have [SURROUND Australia Pty Ltd](https://surroundaustralia.com) join the W3ID Consortium and have been advised by existing members via email that I should open an Issue like this.
> 
> So, please allow SURROUND in! Thanks.
> 
> [1] https://lists.w3.org/Archives/Public/public-perma-id/2020Dec/0004.html

Supported.

I believe @msporny should be able to handle the rest of this matter.

**Comment by msporny** [comment]
> I believe @msporny should be able to handle the rest of this matter.

+1 to extend the consortium to SURROUND Australia -- the only action items are:

1. Add @nicholascar with commit rights to the repo.
2. Add @nicholascar (or someone at SURROUND) with ssh access to w3id.org.
3. Add SURROUND to the landing page as one of the organizations -- we'll want to remove some of the other organizations that have gone missing in the last 5 years.

@nicholascar -- it might be useful for you and I to have a call in the new year so that you understand the expectations wrt. being a backing organization for w3id.org.

**Comment by nicholascar** [comment]
> call in the new year

Sure. I'm around between XMas & NZ but then away until Jan 18. Happy to wait until Jan18+ if you're not around till then.

**Comment by nicholascar** [comment]
Hi @msporny are you available for a chat some day about now? Thanks,

**Comment by dgarijo** [comment]
After this is done, I think the process should be a little more streamlined in case new contributors want to join the group to help maintain w3id. Maybe in the main page?

**Comment by nicholascar** [comment]
Hi @msporny are you available for a chat this week or next?

**Comment by nicholascar** [comment]
Double bump @msporny!

@kidehen can you perhaps assist further?

**Comment by nicholascar** [comment]
Radio silence... guys, this is why you need Orgs to join this consortium! If @msporny is not available, perhaps @dgarijo, @kidehen or anyone else can assist? I'm just @... people's names here at this point to see if I can get a response...

**Comment by dgarijo** [comment]
@nicholascar,
I share your frustration, I think this process should be better outlined. Unfortunately, I am only a collaborator and cannot add any collators to the repository. @davidlehn can we please make @nicholascar a collaborator until the rest of the details are fleshed out?
The list of 3 TODOs posted by @msporny takes just a few minutes to complete. It's been three months...

**Comment by davidlehn** [comment]
@nicholascar Sorry about the silence.  I think we've all just been busy.  I think it's fine to add your organization.  We just haven't setup anything formal as how to do so.  I'm not sure what the rights and responsibilities of new (and old!) organizations should be.  From an operational view, we haven't been crushed under our own weight yet, and things have been going fairly smoothly, if a bit ad-hoc.

As far as @msporny's action items.  We probably should have some better docs on procedures for those with commit access.  It's been mostly @dgarijo and myself handling the day-to-day updates.  I'm not sure if we should have such docs in place before adding new committers or not.

For ssh access I think only Digital Bazaar people have access right now.  That's partly due to security, and partly because there's usually not much to be done but occasional updates and such.  If others want to be a backup to handle issues, we can certainly figure out the details.

Adding a new org is easy, I think we can just go ahead and do that since no one is objecting.  Feel free to make a PR (maybe with a `<ul>` vs the inline text).  I'm not sure what the process or policy is for removing older organizations.  I think we should contact orgs before removing them.  There hasn't been much to do that required actions from all the orgs, so low activity is to be expected.  But yeah, we should vet the list from time to time.

If we need to do call(s) that's fine.  Further discussion here works too.

**Comment by nicholascar** [comment]
>  I think it's fine to add your organization.

Great, thanks!

> We just haven't setup anything formal as how to do so

Understood: one never needs to until one actually needs to!

> We probably should have some better docs on procedures for those with commit access

Happy to help with this, now that I'm part of a maintainer. I'd like to, slowly, go through all the best practice things for PIDs and tick them off. I've published about this sort of thing before, see [1], and I'm not saying I have all the answers at all, but I would like to see what I and others thought would be _best practice_ there and in other literature and see where W3ID sits comparatively. I'm doing something similar for the Australian Government Linked Data PIDs that I help manage too. In the Australian government case, we are moving to a customized IRI Registry Model [2] and tooling (a CMS to manage the data and built the mappings) that is probably worth some discussion at some point.

> For ssh access... If others want to be a backup to handle issues, we can certainly figure out the details.

I think this is necessity. I'm not necessarily volunteering but 2+ parties have to have all areas access, just in case.

> Feel free to make a PR (maybe with a `<ul>` vs the inline text).

OK, I've done so, see PR #2058

>  I think we should contact orgs before removing them

Agreed. I'll wait until PR #2058's merged and then will assist with this if you like. Or you, as a maintainer with longer history here, could email around. I contacted 3RoundStones already (I know Bernadette) and I'm pleased to see their website it back online.

[1] Car, N J, Golodoniuc, P and Klump, J (2017). _The challenge of ensuring persistency of identifier systems in the world of ever-changing technology_. Data Science Journal **16** (13): 1–18, DOI: <https://doi.org/10.5334/dsj-2017-013>

[2] <https://github.com/AGLDWG/iri-registry-ont>

**Comment by davidlehn** [comment]
- We added SURROUND to list of maintainers on homepage in https://github.com/perma-id/w3id.org/pull/2058.
- @msporny: @nicholascar should be given commit access. (I assume, unless we wanted more procedural docs first.).  As pointed out https://github.com/perma-id/w3id.org/pull/2063, @dgarijo and I don't have admin access to this org to do this.
- I'm not sure what we're doing about direct server access.

**Comment by nicholascar** [comment]
Thanks @davidlehn & @dgarijo! 

I'll slowly start to propose some procedures / governance patterns such as named role lists (people proposing PIDs, people approving them, people managing the technical systems etc.) in line with standards for such things (ISO 19165 or ISO 11179). the roles are pretty simple, so I'll post some info about them as a first step and then we can, likely easily, identify who is playing them and record that somewhere.

**Comment by dgarijo** [comment]
Can this issue be closed?

**Comment by nicholascar** [comment]
Well I guess I've long been in the perma-id fold and listed on the main page so yes. 

It would be good to document a bit better how the pattern provisioning works, i.e. what things are watching this repo in order to update the server at w3id.org and other things which go to the long-term maintenance of the system, but I will make other tickets for them!
