### ISSUE TITLE
Intermittent 404 errors from previously consistent URL mappings

### ISSUE THREAD

**Issue by sierra-moxon** [perma-id/w3id.org#2434]
For many hours this morning (Dec/08/2021 Pacific Time), we have noticed inconsistent downtime of the following URLs that have previously been reliable for many months.  We use these redirects very often as part of our software builds, so the downtime is affecting development.  

curl -L https://w3id.org/linkml/types.yaml fails with the message:
curl: (28) Failed to connect to w3id.org port 443: Operation timed out

but one out of every 10 tries generates the proper response:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://linkml.github.io/linkml-model/linkml_model/model/schema/types.yaml">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at w3id.org Port 443</address>
</body></html>
```
similar behavior when attempted in the browser directly.

We also tried different organizational redirects like this one:  https://w3id.org/sssom and it too is intermittently failing to resolve.

@cmungall

**Comment by davidlehn** [comment]
The networking has been weird for ~2h.  I was hoping it would resolve itself.  The alerts we get are showing the connections from various regions bouncing up and down.  If it goes on much longer I'll file a ticket with the hosting provider.

I'd also consider adding a fallback to local cached resources if possible rather than depending on networked resources to always be available.

**Comment by sierra-moxon** [comment]
Thank you so much for your prompt reply!  We very much appreciate it.  :)

**Comment by davidlehn** [comment]
It stopped bouncing up and down 30 minutes ago, I'll assume networking fixed itself.
